{
	"version": 1740571160,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/harry-sheet0.png",
		"images/bg-sheet0.png",
		"images/deatheater-sheet0.png",
		"images/deatheater-sheet1.png",
		"images/l1-sheet0.png",
		"images/diamond-sheet0.png",
		"images/diamond-sheet1.png",
		"images/particlessnitch.png",
		"images/particlescloak.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/collect diamond.m4a",
		"media/collect diamond.ogg",
		"media/game over (2).m4a",
		"media/game over (2).ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"media/whale sound.m4a",
		"media/whale sound.ogg",
		"media/game over (5).m4a",
		"media/game over (5).ogg",
		"media/dementors sound 2.m4a",
		"media/dementors sound 2.ogg",
		"media/booster powerup double score normal score sound.m4a",
		"media/booster powerup double score normal score sound.ogg",
		"media/bg (4).m4a",
		"media/bg (4).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}